### ISSUE TITLE
pathname specific params

### ISSUE THREAD

**Issue by dmitkataev** [Treora/redux-query-sync#17]
Let's consider the following case:
www.test.com/catalog1?sortField=fld1&sordDirection=desc&filter='some filter'
and another one is
www.test.com/catalog2?sortField=fld2&sortDirection=asc&filter="another filter'
These are two different pathnames and they contain absolutely different info and has its own state in store.
So my proposal is to make it possible to define a pathname depended params and also keep the current way of working with not path related params.
The config can look like this:

```
ReduxQuerySync({
    store,
    params: {
      pathSpecific: [{
         pathname: /^www\.test\.com\/catalog1\/.*/,
         params: { 
             sortField: {
                 selector: sel1,
                 action: act1,
                 defaultValue: def1,
             },
             sortDirection: {},
             filter: {}
         }
      }, {
        pathname: /^www\.test\.com\/catalog2\/.*/,
        params: {
            sortField: {
                selector: sel2,
                action: act2,
                defaultValue: def2,
            },
            sortDirection: {},
            filter: {}
        }
      }],
      ... //other not path specific params
   },
})
```
I did implement this idea already because I need this behavior in my project.
What do you think @Treora ? I also thought that for not path related params it could be just empty pathname, then we don't need to separate path specific and not path specific params.

**Comment by Treora** [comment]
See #7. As I explained [there](https://github.com/Treora/redux-query-sync/issues/7#issuecomment-321996258):
> My intuition tells me however that this module should be indifferent to paths or other parts of its environment. I think it should rather give you the possibility to easily change its configuration, so you can still implement the desired behaviour.

Your suggested API seems practical, but it requires us to make decisions about which parts of the context one can make their configuration dependent on (in your case the context is the path, but one might want to make `config.params` depend on some redux state, or a window size, etc.), and also how those are to be specified (by regexes, in your example).

To keep this module modular, and not attempt to become a full router (feel free to fork and do that!), I would prefer to remain unopinionated about anything besides query parameters. In #7 I already gave an example to switch between configs. I welcome API proposals that make such switching easier!

@dmitkataev I'd be happy to hear whether you agree, or if you are of the opinion that paths are a special case that are worth handling inside this module.

**Comment by dmitkataev** [comment]
> I'd be happy to hear whether you agree, or if you are of the opinion that paths are a special case that are worth handling inside this module.

Well, I agree with you.  But idea with switching config is a bit complex.
ReduxQuerySync({
  getContext: (location, state) => ..., // returns 'context1' or 'context2' depending on our logic 
  params: {
     context1: { ... },
     context2: { ... },
  }
})

In example above we give a user possibility to deside which context to use depending on current location and/or state.

**Comment by Treora** [comment]
Closing this issue. As discussed above, providing configuration per path does not seem a desirable approach.
Nevertheless some approach to make configuration context-dependent, or more easily modified, may be worth considering.
