### ISSUE TITLE
Provide a full working example

### ISSUE THREAD

**Issue by nhooey** [Treora/redux-query-sync#21]
It would help to have a fully working React example app that uses a Redux store, to make it easier to understand how to use this module in an existing project.

**Comment by Treora** [comment]
A simple example to point at may be nice, especially one that people can try out directly. If anyone has made a simple use case that we could link to, let know.

**Comment by nhooey** [comment]
I doubt anyone is watching this issue and will notice your request for a fully-working example. Could you make one?

You could just edit `jackielii/simplest-redux-example` or something similar.

**Comment by J-F-Far** [comment]
@Treora @nhooey If you are still looking for a very simple working example project you can check out my repo https://github.com/J-F-Far/url-redux-sync. I needed to 'see' this working before I could be confident that it would work for a different project. It is built using CRA, which most people are familiar with. If you want to me change or add anything, I'll do my best to accommodate.

**Comment by Treora** [comment]
@J-F-Far I appear to have missed your contribution for nearly a year, my apologies! Thanks for sharing your example. I added a link to your example in the readme. If you’d prefer the freedom to remove your repo without breaking the link, I could also clone it and link to the clone instead.
