### ISSUE TITLE
Does redux-query-sync work with Url hashes?

### ISSUE THREAD

**Issue by Sherlock92** [Treora/redux-query-sync#25]
Hey, thanks for the great library. In our app we have routes like `/hello/world/#/?type=foo`. It seems that the library doesn't work with this kind of url, since the values are not being read/applied to the store. Is there a way of getting it to read/write the search query after the hash?

Thanks

**Comment by Treora** [comment]
This library is indeed not made with such uses in mind. If you wish to make it work still, you could try change the three places where `location.search` is being read, making them read `location.hash.substring(location.hash.indexOf('?'))` instead. And likewise change the [lines](https://github.com/Treora/redux-query-sync/blob/90e97694c06d2dc42173d206f1756e7c4e56c0d5/src/redux-query-sync.js#L137-L138) where `newLocation` is being made, to something like this:
```
  search: location.search,
  hash: location.hash.substring(0, location.hash.indexOf('?')) + newLocationSearchString.
```

I have not tested this, so I have probably still missed some details. Happy to hear if you get it to work.

**Comment by Sherlock92** [comment]
Thanks, I managed to get it working for our specific use case.
