### ISSUE TITLE
If condition of deleting location param doesn't support deep comparison 

### ISSUE THREAD

**Issue by nettree** [Treora/redux-query-sync#35]
We notice in line 121 of `handleStateUpdate` method, the logic of checking if a location param needs to be deleted doesn't support deep comparison
```
    if (value === defaultValue) {
        locationParams.delete(param);
    }
```
We have situation when initial value for a state is an `[]`, and since `[] === []` returns false, it doesn't delete this parameter from URL, thus leave something like `?param=`, can we please add support for deep comparison so that it can also check object equality?

**Comment by Treora** [comment]
So far it has not seemed worth providing a way to customise the equality test; and hard-coding any other test than strict equality seems a bit arbitrary (or at least I would not know an obvious choice).

In issue #15, which boils down to the same question, a [workaround](https://github.com/Treora/redux-query-sync/issues/15#issuecomment-329989330) came up: converting your array to a string already in the `selector`, set the `defaultValue` to `'[]'`, and then the comparison will consider `'[]' === '[]'` to be true.

If that suffices for you, feel free to close this issue, or if you have thought out a proposal that seems worthwile to you, feel free to share it.

**Comment by nettree** [comment]
Thank you @Treora, will have a look at that workaround to see if that works in our case. :)

**Comment by nettree** [comment]
Hi @Treora, I tried with the workaround and it seems working quite well, my code is like:
```
{
    selector: state => JSON.stringify(state.xxx.xxx),
    action: query => youAction(query),
    stringToValue: value => yourStringToValue(value),
    valueToString: queries => youValueToString(JSON.parse(queries)),
    defaultValue: '[]'
}
```
So the difference is we change default value to `'[]'` from `[]` and use `JSON.stringify` to convert our state object to string, then use `JSON.parse` to convert the string back to object to make sure the `valueToString` functional. 

Happy to close the ticket, thank you for your help @Treora :)
