### ISSUE TITLE
Add support for Reach-Router

### ISSUE THREAD

**Issue by timmysmalls** [Treora/redux-query-sync#38]
I've been working with this package (many thanks, helped me out a lot!) for a Gatsby site, and ran into some compatibility issues because Gatsby uses Reach router. I changed some things around to make Reach router play nice with your package. The changes are pretty minimal. I'd like to add those changes to your repo (after clearning everything up), if you're up for supporting both React Router and Reach router?

**Comment by Treora** [comment]
Glad it helps you! Regarding compatibility issues, could you tell what 
causes the issue? And show your solution if you have it already? If it 
is a clean small change with which the module will still make sense by 
itself, that would be fine. On the other hand, if it feels like we are 
adding workarounds to make it compatible with this specific router, it 
might be worth seeing if the fix could be done in the router instead. 
But we first need to see what is the problem!

**Comment by timmysmalls** [comment]
As far as I can tell the main difference between the two routers that affect this package is the arguments with which the eventhandler gets called on page changes. Other than that the two are very similar. Reach was created by one of the guys that created React router. I think perhaps an extra optional argument like "useReach: true" in the config could be all that's necessary. And then an optional import in case this argument is passed, so that it imports the historyListener from Reach, and subscribes to that listener to be alerted on page changes. I'll upload the changes I made this week. so you can check it out and see what you think. Should be very minimal. Thanks!

**Comment by timmysmalls** [comment]
Getting it to work was quite easy, I have the version with my additional commit up on GitHub. All that's required to get it to work is to pass a custom history object to the middleware, which should the `globalHistory` object that comes with Reach router. Then you need to pass a flag `reach: true` to make two minor changes to the way the module works.

It shouldn't cause any issues, and it's very straightforward, but I'm not entirely happy with the way it panned out. I can live with the monkeypatch function, as it's just there to make the two API's compatible, but I'm not too thrilled about using the `globalHistory` module. Unfortunately Reach router's documentation is too limited at this point to be able to come up with something cleaner. In fact, as far as I can tell, the `globalHistory` object is not even mentioned in their docs at all.

So it's nice that I got it to work, but integrating it in other packages is probably not a good idea yet. Perhaps in the future.
