### ISSUE TITLE
Example -  NOT FOUND

### ISSUE THREAD

**Issue by giovannicassanelli-cell** [Treora/redux-query-sync#40]
The example given by JFFar is not working anymore, someone has a copy of it and want to share it ?
[https://github.com/J-F-Far/url-redux-sync/blob/master/src/index.js]

**Comment by Treora** [comment]
Searching the repo name on github reveals a clone here: https://github.com/aruncoderenthu/url-redux-sync

I removed the broken link from the readme, and replaced it with a link to another usage of this module (in fact my initial use case).
