### ISSUE TITLE
Is it possible to use this only on certain pathname?

### ISSUE THREAD

**Issue by penguin-ninja** [Treora/redux-query-sync#7]
I would like to apply sync query to different states on different paths.

For example, let's say there are two paths.

```
/books?page=1
/computers?page=1
```

I would like to know if i can create enhancer like this.

```
ReduxQuerySync.enhancer({
    params: {
        page: [{
           path: '/books'
           ... // actions, selectors, etc
        }, {
           path: '/computers'
        }]
    },
})
```

**Comment by penguin-ninja** [comment]
Or at least is it possible to provide current pathname to actions and selectors?

**Comment by Treora** [comment]
It would be nice to enable your use case. My intuition tells me however that this module should be indifferent to paths or other parts of its environment. I think it should rather give you the possibility to easily change its configuration, so you can still implement the desired behaviour.

A rough and untested sketch of how this might currently be done:
```
const querySyncParamsByPath = {
    '/books': {/* action, selector, ... */},
    '/computers': {/* action, selector, ... */},
}

let unsubscribeQuerySync
function onPathChange() {
    const path = /* read current path */
    unsubscribeQuerySync && unsubscribeQuerySync()
    unsubscribeQuerySync = ReduxQuerySync({
        params: querySyncParamsByPath[path],
        ...otherSettings
    })
}
yourRouterOrWhatever.someRoutingEvent.addListener(onPathChange)
```

What is still missing is a possibility to remove parameters from the query, so they don't linger after a path change. It may be worth providing a way to do this. Perhaps by passing something like `{hideParams: true}` to `unsubscribeQuerySync`?

I would be happy to hear suggestions for other simple changes to the API that would allow more versatile usage.

**Comment by Treora** [comment]
> Or at least is it possible to provide current pathname to actions and selectors?

I don't think this module should provide it, as it is not obvious to me that the path is more important than any other piece of the environment, but feel free to convince me otherwise.

You could read the path in the functions themselves, e.g.: `action: value => myActionCreator(value, window.location.pathname)`.

**Comment by penguin-ninja** [comment]
Thanks for your kind reply @Treora 

`unsubscribeQuerySync()` 

If I call `ReduxQuerySync()()`, then does it unsubscribe to store? If it provides unsubscribing to store, I think that would be the easiest way.

**Comment by Treora** [comment]
> If I call ReduxQuerySync()(), then does it unsubscribe to store?

Yes, it unsubscribes from both the store and changes to the location. (see [source code](https://github.com/Treora/redux-query-sync/blob/dac493424ebe997470e0b62b3d54ac49159403bf/src/redux-query-sync.js#L146-L149))

If this seems a good enough solution, I'll just close this issue now. Feel free to reopen or open a new issue if you have suggestions for API improvements.

**Comment by penguin-ninja** [comment]
👍  yes I think this will solve the issue for now.
