### ISSUE TITLE
Stop relying on experimental URL API (to e.g. support IE&Edge)

### ISSUE THREAD

**Issue by cadrell0** [Treora/redux-query-sync#8]
This currently does not work in IE or Edge as they do not support Url("").searchParams. Maybe just including a polyfill will fix it?

**Comment by Treora** [comment]
Thanks for pointing this out. Using this experimental API was a quick solution but not the best choice for wider adoption. Apparently it has only been spec'd by the WHATWG group ([here](https://url.spec.whatwg.org/#interface-urlsearchparams)), and currently only works in recent Firefox and Chrome|ium ([says MDN](https://developer.mozilla.org/en-US/docs/Web/API/URL/searchParams#Browser_compatibility)).

Either a polyfill should indeed be included ([this one](https://github.com/webcomponents/URL) seems most referred to), or alternatively any other method of reading and writing the parameters could be used instead, e.g. using [query-string](https://github.com/sindresorhus/query-string) or [url-params](https://github.com/AtenDesignGroup/url-params).

I may not have time for this anytime soon, but PRs are very welcome! :)

**Comment by cadrell0** [comment]
I've been using https://github.com/WebReflection/url-search-params on my current project. I'll try to put together a PR this weekend. This has the added benefit of not needing to prepend a dummy url before parsing.

**Comment by Treora** [comment]
Fixed by #12.
